name: desync
base: core20
version: git
summary: Alternative casync implementation
description: |
 This project re-implements many features of upstream casync in Go.
 It seeks to maintain compatibility with casync's data structures,
 protocols and types, such as chunk stores (castr), index files (caibx/caidx)
 and archives (catar) in order to function as a drop-in replacement in many
 use cases. It also tries to maintain support for platforms other than Linux
 and simplify build/installation. It consists of a library that implements the
 features, available for integration into any 3rd-party product as well as a
 command-line tool. 

grade: devel
confinement: strict
compression: lzo

parts:
  desync:
    plugin: go
    source: .

apps:
  desync:
    command: bin/desync
    plugs:
      - home

